### ISSUE TITLE
Dati nazionali e dati regionali non coincidono

### ISSUE THREAD

**Issue by ebobferraris** [immuni-app/immuni-dashboard-data#2]
La somma dei casi totali nella tabella regionale è pari a 1.122, mentre quella dei casi totali nella tabella nazionale per lo stesso periodo è pari a 1.390 (2020-06-15 > 2020-10-25 compresi).

Nella tabella dei dati nazionali risultano 21 utenti positivi a giugno e 38 utenti positivi a luglio, sulla tabella dei dati regionali risultano 6 soli casi in Lombardia nella settimana del 2020-06-29.

Nella tabella dei dati nazionali risultano 98 utenti positivi ad agosto, sulla tabella dei dati regionali risultano 32 soli casi ad agosto nelle settimane del 2020-08-10 (6) e del 2020-08-24 (26), oltre a quelli del giorno 31/08 di cui non esiste dettaglio (a livello nazionale nella giornata del 31/08 sono presenti 8 positivi).

Tutte le successive settimane presentano una discrepanza di alcune unità.

**NB:** nella lettura dei dati regionali è stata presa come data iniziale quella indicata nella prima colonna e data finale la domenica successiva (e.g. 2020-06-15 > 2020-06-21 compresi).

**Comment by immuniteam** [comment]
Ciao @ebobferraris grazie per la tua segnalazione. Leggendo la [documentazione](https://github.com/immuni-app/immuni-dashboard-data/blob/master/format-regional-trend.md) del trend regionale viene riportato quanto segue: 

> *If this value is negative (-1), the number of notifications or positive users is less than or equal to 5.

 Pertanto non è possibile effettuare la somma sul trend regionale e rapportarlo al trend nazionale, quindi è del tutto normale che sull'intero arco temporale accumuli errore sui valori. 

Per il momento chiudiamo la issue e grazie per aver contribuito.
