### ISSUE TITLE
Interpretation of the warning data comment

### ISSUE THREAD

**Issue by leonardomaccari** [immuni-app/immuni-dashboard-data#5]
Hello, 
first of all, kudos for this effort. This is possibly the most complete data set of all the contact tracing apps. 

I need to understand better this sentence:

> The number of notifications is the number of notifications of possible risk exposure generated by the application. The detection is partial since all notifications for iOS devices are detected and only a third of those sent by Android that have the necessary technology available to detect them safely.

This means that 

notifiche_inviate = (total notifications for IoS) + (total notification for Android)/3

is this a correct interpretation?

**Comment by immuniteam** [comment]
Hi @leonardomaccari, thanks for your feedback and for contributing to the community with this issue.
Your interpretation is correct, it is estimated that only a third of Android devices have the necessary technology available to detect the notification sent safely (android notifications / 3 ), please note that this number at the denominator (i.e 3) is not necessarily constant over time.
